package projek;


import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Siti Afiyah
 */
public class Fraame1 extends javax.swing.JFrame {

    /**
     * Creates new form Fraame1
     */
    public Fraame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator3 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        user = new javax.swing.JTextField();
        pass = new javax.swing.JTextField();
        EXIT = new javax.swing.JButton();
        LOG = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();

        jSeparator3.setForeground(new java.awt.Color(0, 0, 51));
        jSeparator3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N

        jLabel6.setText("jLabel6");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTabbedPane1.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N

        jPanel3.setLayout(null);
        jPanel3.add(jLabel7);
        jLabel7.setBounds(20, 250, 180, 120);
        jPanel3.add(jLabel8);
        jLabel8.setBounds(250, 250, 180, 120);
        jPanel3.add(jLabel9);
        jLabel9.setBounds(470, 250, 0, 120);

        jLabel10.setBackground(new java.awt.Color(255, 255, 255));
        jLabel10.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("13 - I'in Nuraini");
        jPanel3.add(jLabel10);
        jLabel10.setBounds(50, 370, 140, 30);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("33 - Siti Afiyah");
        jPanel3.add(jLabel11);
        jLabel11.setBounds(280, 370, 130, 30);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("20 - M. Iqbal Samudra");
        jPanel3.add(jLabel12);
        jLabel12.setBounds(360, 180, 170, 30);

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("34 - Tiara Eka Deliya");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(480, 370, 160, 30);

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("11 - Fandi Khusnu P.");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(130, 180, 160, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/1.JPG"))); // NOI18N
        jPanel3.add(jLabel18);
        jLabel18.setBounds(110, 60, 175, 120);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/2.JPG"))); // NOI18N
        jPanel3.add(jLabel20);
        jLabel20.setBounds(350, 60, 180, 120);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/3.JPG"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(30, 250, 180, 120);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/4.JPG"))); // NOI18N
        jPanel3.add(jLabel4);
        jLabel4.setBounds(250, 250, 180, 120);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/5.JPG"))); // NOI18N
        jPanel3.add(jLabel16);
        jLabel16.setBounds(460, 250, 175, 116);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/FRAME 2.1.png"))); // NOI18N
        jPanel3.add(jLabel17);
        jLabel17.setBounds(0, -10, 677, 460);

        jTabbedPane1.addTab("About Us", jPanel3);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Debby", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("User");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(310, 120, 60, 30);

        jLabel3.setFont(new java.awt.Font("Debby", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(280, 210, 120, 30);

        user.setFont(new java.awt.Font("Ailerons", 0, 24)); // NOI18N
        user.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        user.setBorder(null);
        jPanel1.add(user);
        user.setBounds(240, 160, 180, 30);

        pass.setFont(new java.awt.Font("Ailerons", 0, 24)); // NOI18N
        pass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(pass);
        pass.setBounds(240, 250, 180, 30);

        EXIT.setBackground(new java.awt.Color(255, 255, 255));
        EXIT.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        EXIT.setText("EXIT");
        EXIT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXITActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT);
        EXIT.setBounds(350, 310, 130, 40);

        LOG.setBackground(new java.awt.Color(255, 255, 255));
        LOG.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        LOG.setText("LOGIN");
        LOG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGActionPerformed(evt);
            }
        });
        jPanel1.add(LOG);
        LOG.setBounds(190, 310, 130, 40);

        jLabel15.setFont(new java.awt.Font("Ailerons", 0, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("LOGIN");
        jPanel1.add(jLabel15);
        jLabel15.setBounds(260, 40, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/FRAME 2.1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 670, 581);

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(210, 200, 240, 10);

        jTabbedPane1.addTab("Login", jPanel1);

        getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 140, 680, 490);

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/Frame 3.png"))); // NOI18N
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 4, 680, 550);

        setBounds(0, 0, 692, 668);
    }// </editor-fold>//GEN-END:initComponents

    private void EXITActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXITActionPerformed
        System.exit(0);
        
        // TODO add your handling code here:
    }//GEN-LAST:event_EXITActionPerformed

    private void LOGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGActionPerformed
       if(user.getText().trim().equals("user") && pass.getText().trim().equals("user")){
            JOptionPane.showMessageDialog(null, "Selamat Anda Masuk Sebagai User!!!");
            new Frame1().setVisible(true);
            dispose();}
       else{
            JOptionPane.showMessageDialog(null, "Maaf UserName dan Password yang anda Masukan Salah !!");
            Fraame1 f = new Fraame1();
                    f.show();
                    this.dispose();
                
     
            //JOptionPane.showMessageDialog(null, "Maaf Username dan Password yang Anda Masukan Salah!!!");
        }
        
          
    }//GEN-LAST:event_LOGActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fraame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fraame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fraame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fraame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fraame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT;
    private javax.swing.JButton LOG;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField pass;
    private javax.swing.JTextField user;
    // End of variables declaration//GEN-END:variables

}
