/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek;

/**
 *
 * @author Siti Afiyah
 */
public class Frame2 extends javax.swing.JFrame {

    /**
     * Creates new form Frame2
     */
    public Frame2(String nama, String alamat, String berat, String nohp, String tgl, String paket, int harga ) {
        initComponents();
        // paket, berat , harga
        Hasil1.setText(nama);
        Hasil2.setText(alamat);
        Hasil3.setText(berat);
        Hasil4.setText(nohp);
        Hasil5.setText(tgl);
        Hasil6.setText(paket); 
        Hasil7.setText(String.valueOf(harga));
    }

    Frame2() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Frame2(String paket, String berat) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    Frame2(String nama, String alamat, String tgl, String paket, String berat) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        Hasil7 = new javax.swing.JLabel();
        Hasil1 = new javax.swing.JLabel();
        Hasil2 = new javax.swing.JLabel();
        Hasil3 = new javax.swing.JLabel();
        Hasil4 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Hasil5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        Hasil6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 180, 70, 30);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Paket Berat");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 220, 100, 30);

        jLabel6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. Telp");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 260, 70, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Paket");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 340, 90, 30);

        jLabel9.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText(":");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(170, 380, 30, 30);

        jLabel10.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText(":");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(170, 140, 70, 30);

        jLabel11.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText(":");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(170, 180, 70, 30);

        jLabel12.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText(":");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(170, 220, 70, 30);

        jLabel13.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText(":");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(170, 260, 70, 30);

        Hasil7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Hasil7.setForeground(new java.awt.Color(255, 255, 255));
        Hasil7.setText("Hasil7");
        getContentPane().add(Hasil7);
        Hasil7.setBounds(260, 380, 110, 30);

        Hasil1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Hasil1.setForeground(new java.awt.Color(255, 255, 255));
        Hasil1.setText("Hasil1");
        getContentPane().add(Hasil1);
        Hasil1.setBounds(220, 140, 150, 30);

        Hasil2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Hasil2.setForeground(new java.awt.Color(255, 255, 255));
        Hasil2.setText("Hasil2");
        getContentPane().add(Hasil2);
        Hasil2.setBounds(220, 180, 150, 30);

        Hasil3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Hasil3.setForeground(new java.awt.Color(255, 255, 255));
        Hasil3.setText("Hasil3");
        getContentPane().add(Hasil3);
        Hasil3.setBounds(220, 220, 130, 30);

        Hasil4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Hasil4.setForeground(new java.awt.Color(255, 255, 255));
        Hasil4.setText("Hasil4");
        getContentPane().add(Hasil4);
        Hasil4.setBounds(220, 260, 150, 30);

        jLabel19.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Tanggal Ambil");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(50, 300, 110, 30);

        jLabel20.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText(":");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(170, 300, 70, 30);

        Hasil5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Hasil5.setForeground(new java.awt.Color(255, 255, 255));
        Hasil5.setText("Hasil5");
        getContentPane().add(Hasil5);
        Hasil5.setBounds(220, 300, 150, 30);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Harga");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 380, 70, 30);

        jLabel14.setFont(new java.awt.Font("Square721 BT", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText(":");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(170, 340, 70, 30);

        Hasil6.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Hasil6.setForeground(new java.awt.Color(255, 255, 255));
        Hasil6.setText("Hasil6");
        getContentPane().add(Hasil6);
        Hasil6.setBounds(220, 340, 150, 30);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Nama");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 140, 60, 30);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(330, 260, 90, 60);

        jLabel16.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Rp.");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(220, 380, 30, 30);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/frame5.png"))); // NOI18N
        getContentPane().add(jLabel15);
        jLabel15.setBounds(0, -6, 440, 550);

        setBounds(0, 0, 456, 580);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame2().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Hasil1;
    private javax.swing.JLabel Hasil2;
    private javax.swing.JLabel Hasil3;
    private javax.swing.JLabel Hasil4;
    private javax.swing.JLabel Hasil5;
    private javax.swing.JLabel Hasil6;
    private javax.swing.JLabel Hasil7;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
