/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projek;

import java.awt.event.KeyEvent;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane; 

/**
 *
 * @author Siti Afiyah
 */
public class Frame1 extends javax.swing.JFrame {

    /**
     * Creates new form Frame1
     */
    public Frame1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Frame1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        eNama = new javax.swing.JTextField();
        ePB = new javax.swing.JTextField();
        NOP = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        eAlamat = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TGL = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Frame1.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Amatic SC", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tanggal Ambil");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(50, 200, 120, 30);

        jLabel3.setFont(new java.awt.Font("Amatic SC", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(50, 30, 80, 40);

        jLabel4.setFont(new java.awt.Font("Amatic SC", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Alamat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(50, 80, 100, 30);

        jLabel5.setFont(new java.awt.Font("Amatic SC", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Paket Berat");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(50, 120, 100, 30);

        jLabel6.setFont(new java.awt.Font("Amatic SC", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("No. Telp");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(50, 160, 100, 30);
        jPanel1.add(eNama);
        eNama.setBounds(170, 40, 230, 30);

        ePB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ePBActionPerformed(evt);
            }
        });
        ePB.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ePBKeyTyped(evt);
            }
        });
        jPanel1.add(ePB);
        ePB.setBounds(170, 120, 190, 30);

        NOP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NOPActionPerformed(evt);
            }
        });
        jPanel1.add(NOP);
        NOP.setBounds(170, 160, 230, 30);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        jButton1.setText("Ok");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(320, 250, 90, 40);

        jLabel7.setFont(new java.awt.Font("Amatic SC", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("PAKET");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(480, 40, 90, 30);

        buttonGroup1.add(rb1);
        rb1.setFont(new java.awt.Font("Amatic SC", 0, 18)); // NOI18N
        rb1.setForeground(new java.awt.Color(255, 255, 255));
        rb1.setText("Cuci Kering");
        jPanel1.add(rb1);
        rb1.setBounds(480, 80, 120, 30);

        buttonGroup1.add(rb2);
        rb2.setFont(new java.awt.Font("Amatic SC", 0, 18)); // NOI18N
        rb2.setForeground(new java.awt.Color(255, 255, 255));
        rb2.setText("Cuci Kering Setrika");
        jPanel1.add(rb2);
        rb2.setBounds(480, 110, 180, 30);

        buttonGroup1.add(rb3);
        rb3.setFont(new java.awt.Font("Amatic SC", 0, 18)); // NOI18N
        rb3.setForeground(new java.awt.Color(255, 255, 255));
        rb3.setText("Setrika");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        jPanel1.add(rb3);
        rb3.setBounds(480, 140, 100, 30);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        jButton2.setText("Clear");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 250, 100, 40);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Debby", 0, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(540, 320, 100, 40);

        eAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eAlamatActionPerformed(evt);
            }
        });
        jPanel1.add(eAlamat);
        eAlamat.setBounds(170, 80, 230, 30);

        jLabel8.setFont(new java.awt.Font("Amatic SC", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("kg");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(370, 120, 20, 30);
        jPanel1.add(TGL);
        TGL.setBounds(170, 200, 240, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/Frame4.1.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, -80, 670, 460);

        Frame1.addTab("Masukan Data Diri", jPanel1);

        getContentPane().add(Frame1);
        Frame1.setBounds(0, 60, 670, 430);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projek/Frame4.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(-6, 0, 700, 480);

        setBounds(0, 0, 675, 527);
    }// </editor-fold>//GEN-END:initComponents

    private void eAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eAlamatActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        eNama.setText("");
        eAlamat.setText("");
        ePB.setText("");
        buttonGroup1.clearSelection();
        NOP.setText("");

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if(eNama.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap inputkan nama Anda");
        }else if(eAlamat.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap inputkan alamat Anda");
        }else if(ePB.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap inputkan paket berat Anda");
        }else if(NOP.getText().equals("")){
            JOptionPane.showMessageDialog(null, "Harap inputkan no HP Anda");
        }

        String nama = eNama.getText();
        String alamat = eAlamat.getText();
        String berat = ePB.getText() + " kg";

        int hitung = Integer.parseInt(ePB.getText());
        String nohp = NOP.getText();
        SimpleDateFormat dateFormat = new SimpleDateFormat("dd.MM.yyyy");
        String tgl = dateFormat.format(TGL.getDate());
        String paket;
        int harga = 0;

        if(rb1.isSelected())
        paket = "Cuci Kering";
        else if (rb2.isSelected())
        paket = "Cuci Kering Setrika";
        else if (rb3.isSelected())
        paket = "Setrika";
        else
        paket = "";

        if (rb1.isSelected())
        harga = hitung*3000;
        if (rb2.isSelected())
        harga = hitung*4000;
        if (rb3.isSelected())
        harga = hitung*2000;

        if(!(rb1.isSelected() || rb2.isSelected() || rb3.isSelected() )){
            JOptionPane.showMessageDialog(null, "Harap pilih paket layanan");
        }else{
            JOptionPane.showMessageDialog(null, "Data Anda telah lengkap. Tekan OK untuk melihat harga seluruhnya");
            new Frame2(nama, alamat, berat, nohp,tgl, paket, harga).setVisible(true);
            dispose();
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void NOPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NOPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NOPActionPerformed

    private void ePBKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ePBKeyTyped
        char karakter = evt.getKeyChar();
        if(!(((karakter >= '0') && (karakter <= '9') || (karakter == KeyEvent.VK_BACK_SPACE) || (karakter == KeyEvent.VK_DELETE)))){
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_ePBKeyTyped

    private void ePBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ePBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ePBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Frame1;
    private javax.swing.JTextField NOP;
    private com.toedter.calendar.JDateChooser TGL;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField eAlamat;
    private javax.swing.JTextField eNama;
    private javax.swing.JTextField ePB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    // End of variables declaration//GEN-END:variables
}
